project:
  type: website
  output-dir: docs

website:
  title: "Christopher Hussey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: tidydata1.qmd
        text: VIS 1
      - href: tidydata2.qmd
        text: VIS 2
      - href: Project_2.qmd
        text: Project 2
      - href: Project_3.qmd
        text: Project 3
      - href: Project_4.qmd
        text: Project 4
      - href: Project_5.qmd
        text: Project 5
      - href: Final_pres
        text: Final Presentation
      
       

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

