project:
  type: website
  output-dir: docs

website:
  title: "Christopher Hussey"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.html
      - text: "Data Viz"
        menu: 
        - text: Household Plumbing Access
          href: tidydata1.html
        - text: FIDE Ratings by Federation
          href: tidydata2.html
        - text: Netflix Show Patterns
          href: Project_2.html
        - text: Variance in European Recognition Rates of Syrian Refugees
          href: Project_3.html
        - text: Algorithmic Ethics; AFST and Predictive Policing
          href: Project_4.html
        - text: Analyzing Traffic Stops Across California
          href: Project_5.html
        - text: Final Presentation
          href: final_pres.html
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

